---
  - name: Configure Elk VM with Docker
    hosts: elk
    remote_user: RedAdmin
    become: true
    tasks:
      
      # Using apt module to download docker.io
      - name: Install docker.io
        apt:
          update_cache: yes
          force_apt_get: yes
          name: docker.io
          state: present

      # Using apt module to download python3-pip
      - name: Install python3-pip
        apt:
          force_apt_get: yes
          name: python3-pip
          state: present

      # Using pip module to install docker module
      - name: Install Docker module
        pip:
          name: docker
          state: present

      # Using command module to increase virtual memory
      - name: Increase virtual memory
        command: sysctl -w vm.max_map_count=262144

      # Using sysctl module to use more memory
      - name: Use more memory
        sysctl:
          name: vm.max_map_count
          value: 262144
          state: present
          reload: yes

      # Using docker_container module to download the docker elk container
      - name: Download and launch a docker elk container
        docker_container:
          name: elk
          image: sebp/elk:761
          state: started
          restart_policy: always
          published_ports:
            -  5601:5601
            -  9200:9200
            -  5044:5044

      # Using systemd module to enable docker service on boot
      - name: Enable service docker on boot
        systemd:
          name: docker 
          enabled: yes
